kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.internal.hoffmeister.biz/diztortion/getssl
      registry: registry.internal.hoffmeister.biz
